-- Jeu de données des tests d'intégration (Testcontainers), joué par
-- spring.sql.init après que Hibernate a créé le schéma depuis les entités.
--
-- Copie de db/local/V2__seed_local_data.sql, à deux différences près :
--   - l'agence porte l'identifiant 00000000-0000-0000-0000-000000000001, celui
--     que les 45 classes d'intégration attendent (venu de db/migration/V2) ;
--   - pas de compte utilisateur : chaque test crée le sien.
-- Les 39 permissions et le rôle « admin » qui les porte toutes restent.
-- Toutes les permissions que le code nomme dans un hasAuthority / hasAnyAuthority
-- (plus celles du seed local). À régénérer quand une permission apparaît :
--   grep -rhoE "has(Any)?Authority\([^)]*\)" src/main/java | grep -oE "'[a-z0-9-]+'" | sort -u
INSERT INTO permissions (id, name, slug, created_at) VALUES
    (gen_random_uuid(), 'create-appointments', 'create-appointments', NOW()),
    (gen_random_uuid(), 'create-articles', 'create-articles', NOW()),
    (gen_random_uuid(), 'create-banks', 'create-banks', NOW()),
    (gen_random_uuid(), 'create-cashbox-dailies', 'create-cashbox-dailies', NOW()),
    (gen_random_uuid(), 'create-cashbox-ticket-details', 'create-cashbox-ticket-details', NOW()),
    (gen_random_uuid(), 'create-cashbox-tickets', 'create-cashbox-tickets', NOW()),
    (gen_random_uuid(), 'create-category-prestations', 'create-category-prestations', NOW()),
    (gen_random_uuid(), 'create-clients', 'create-clients', NOW()),
    (gen_random_uuid(), 'create-consultations', 'create-consultations', NOW()),
    (gen_random_uuid(), 'create-expence-details', 'create-expence-details', NOW()),
    (gen_random_uuid(), 'create-expenses', 'create-expenses', NOW()),
    (gen_random_uuid(), 'create-movements', 'create-movements', NOW()),
    (gen_random_uuid(), 'create-patients', 'create-patients', NOW()),
    (gen_random_uuid(), 'create-permissions', 'create-permissions', NOW()),
    (gen_random_uuid(), 'create-prestation-orders', 'create-prestation-orders', NOW()),
    (gen_random_uuid(), 'create-prestations', 'create-prestations', NOW()),
    (gen_random_uuid(), 'create-refund-reasons', 'create-refund-reasons', NOW()),
    (gen_random_uuid(), 'create-refund-requests', 'create-refund-requests', NOW()),
    (gen_random_uuid(), 'create-reports', 'create-reports', NOW()),
    (gen_random_uuid(), 'create-supplier-categories', 'create-supplier-categories', NOW()),
    (gen_random_uuid(), 'create-suppliers', 'create-suppliers', NOW()),
    (gen_random_uuid(), 'create-test-orders', 'create-test-orders', NOW()),
    (gen_random_uuid(), 'create-type-consultations', 'create-type-consultations', NOW()),
    (gen_random_uuid(), 'delete-appointments', 'delete-appointments', NOW()),
    (gen_random_uuid(), 'delete-articles', 'delete-articles', NOW()),
    (gen_random_uuid(), 'delete-banks', 'delete-banks', NOW()),
    (gen_random_uuid(), 'delete-cashbox-dailies', 'delete-cashbox-dailies', NOW()),
    (gen_random_uuid(), 'delete-cashbox-ticket-details', 'delete-cashbox-ticket-details', NOW()),
    (gen_random_uuid(), 'delete-cashbox-tickets', 'delete-cashbox-tickets', NOW()),
    (gen_random_uuid(), 'delete-category-prestations', 'delete-category-prestations', NOW()),
    (gen_random_uuid(), 'delete-clients', 'delete-clients', NOW()),
    (gen_random_uuid(), 'delete-consultations', 'delete-consultations', NOW()),
    (gen_random_uuid(), 'delete-expence-details', 'delete-expence-details', NOW()),
    (gen_random_uuid(), 'delete-patients', 'delete-patients', NOW()),
    (gen_random_uuid(), 'delete-permissions', 'delete-permissions', NOW()),
    (gen_random_uuid(), 'delete-prestation-orders', 'delete-prestation-orders', NOW()),
    (gen_random_uuid(), 'delete-prestations', 'delete-prestations', NOW()),
    (gen_random_uuid(), 'delete-refund-reasons', 'delete-refund-reasons', NOW()),
    (gen_random_uuid(), 'delete-refund-requests', 'delete-refund-requests', NOW()),
    (gen_random_uuid(), 'delete-supplier-categories', 'delete-supplier-categories', NOW()),
    (gen_random_uuid(), 'delete-suppliers', 'delete-suppliers', NOW()),
    (gen_random_uuid(), 'delete-test-orders', 'delete-test-orders', NOW()),
    (gen_random_uuid(), 'delete-type-consultations', 'delete-type-consultations', NOW()),
    (gen_random_uuid(), 'deliver-reports', 'deliver-reports', NOW()),
    (gen_random_uuid(), 'edit-appointments', 'edit-appointments', NOW()),
    (gen_random_uuid(), 'edit-articles', 'edit-articles', NOW()),
    (gen_random_uuid(), 'edit-banks', 'edit-banks', NOW()),
    (gen_random_uuid(), 'edit-biology-results', 'edit-biology-results', NOW()),
    (gen_random_uuid(), 'edit-cashbox-dailies', 'edit-cashbox-dailies', NOW()),
    (gen_random_uuid(), 'edit-cashbox-tickets', 'edit-cashbox-tickets', NOW()),
    (gen_random_uuid(), 'edit-category-prestations', 'edit-category-prestations', NOW()),
    (gen_random_uuid(), 'edit-clients', 'edit-clients', NOW()),
    (gen_random_uuid(), 'edit-consultations', 'edit-consultations', NOW()),
    (gen_random_uuid(), 'edit-contrats', 'edit-contrats', NOW()),
    (gen_random_uuid(), 'edit-doctors', 'edit-doctors', NOW()),
    (gen_random_uuid(), 'edit-documentation-categories', 'edit-documentation-categories', NOW()),
    (gen_random_uuid(), 'edit-employees', 'edit-employees', NOW()),
    (gen_random_uuid(), 'edit-hospitals', 'edit-hospitals', NOW()),
    (gen_random_uuid(), 'edit-invoices', 'edit-invoices', NOW()),
    (gen_random_uuid(), 'edit-patients', 'edit-patients', NOW()),
    (gen_random_uuid(), 'edit-permissions', 'edit-permissions', NOW()),
    (gen_random_uuid(), 'edit-prestation-orders', 'edit-prestation-orders', NOW()),
    (gen_random_uuid(), 'edit-prestations', 'edit-prestations', NOW()),
    (gen_random_uuid(), 'edit-refund-reasons', 'edit-refund-reasons', NOW()),
    (gen_random_uuid(), 'edit-refund-requests', 'edit-refund-requests', NOW()),
    (gen_random_uuid(), 'edit-reports', 'edit-reports', NOW()),
    (gen_random_uuid(), 'edit-roles', 'edit-roles', NOW()),
    (gen_random_uuid(), 'edit-settings', 'edit-settings', NOW()),
    (gen_random_uuid(), 'edit-supplier-categories', 'edit-supplier-categories', NOW()),
    (gen_random_uuid(), 'edit-suppliers', 'edit-suppliers', NOW()),
    (gen_random_uuid(), 'edit-test-orders', 'edit-test-orders', NOW()),
    (gen_random_uuid(), 'edit-tests', 'edit-tests', NOW()),
    (gen_random_uuid(), 'edit-tickets', 'edit-tickets', NOW()),
    (gen_random_uuid(), 'edit-type-consultations', 'edit-type-consultations', NOW()),
    (gen_random_uuid(), 'edit-users', 'edit-users', NOW()),
    (gen_random_uuid(), 'manage-antibiotics', 'manage-antibiotics', NOW()),
    (gen_random_uuid(), 'manage-biology-parameters', 'manage-biology-parameters', NOW()),
    (gen_random_uuid(), 'manage-branches', 'manage-branches', NOW()),
    (gen_random_uuid(), 'manage-cashbox', 'manage-cashbox', NOW()),
    (gen_random_uuid(), 'manage-consultations', 'manage-consultations', NOW()),
    (gen_random_uuid(), 'manage-contracts', 'manage-contracts', NOW()),
    (gen_random_uuid(), 'manage-culture-options', 'manage-culture-options', NOW()),
    (gen_random_uuid(), 'manage-doctors', 'manage-doctors', NOW()),
    (gen_random_uuid(), 'manage-employees', 'manage-employees', NOW()),
    (gen_random_uuid(), 'manage-hospitals', 'manage-hospitals', NOW()),
    (gen_random_uuid(), 'manage-inventory', 'manage-inventory', NOW()),
    (gen_random_uuid(), 'manage-invoices', 'manage-invoices', NOW()),
    (gen_random_uuid(), 'manage-payments', 'manage-payments', NOW()),
    (gen_random_uuid(), 'manage-roles', 'manage-roles', NOW()),
    (gen_random_uuid(), 'manage-settings', 'manage-settings', NOW()),
    (gen_random_uuid(), 'manage-support', 'manage-support', NOW()),
    (gen_random_uuid(), 'manage-test-order-assignments', 'manage-test-order-assignments', NOW()),
    (gen_random_uuid(), 'manage-tests', 'manage-tests', NOW()),
    (gen_random_uuid(), 'manage-users', 'manage-users', NOW()),
    (gen_random_uuid(), 'validate-biology-reports', 'validate-biology-reports', NOW()),
    (gen_random_uuid(), 'validate-biology-results', 'validate-biology-results', NOW()),
    (gen_random_uuid(), 'validate-reports', 'validate-reports', NOW()),
    (gen_random_uuid(), 'view-appointments', 'view-appointments', NOW()),
    (gen_random_uuid(), 'view-articles', 'view-articles', NOW()),
    (gen_random_uuid(), 'view-banks', 'view-banks', NOW()),
    (gen_random_uuid(), 'view-biology-results', 'view-biology-results', NOW()),
    (gen_random_uuid(), 'view-cashbox-adds', 'view-cashbox-adds', NOW()),
    (gen_random_uuid(), 'view-cashbox-dailies', 'view-cashbox-dailies', NOW()),
    (gen_random_uuid(), 'view-cashbox-tickets', 'view-cashbox-tickets', NOW()),
    (gen_random_uuid(), 'view-category-prestations', 'view-category-prestations', NOW()),
    (gen_random_uuid(), 'view-clients', 'view-clients', NOW()),
    (gen_random_uuid(), 'view-consultations', 'view-consultations', NOW()),
    (gen_random_uuid(), 'view-contracts', 'view-contracts', NOW()),
    (gen_random_uuid(), 'view-contrats', 'view-contrats', NOW()),
    (gen_random_uuid(), 'view-doctors', 'view-doctors', NOW()),
    (gen_random_uuid(), 'view-documentation-categories', 'view-documentation-categories', NOW()),
    (gen_random_uuid(), 'view-employees', 'view-employees', NOW()),
    (gen_random_uuid(), 'view-expence-details', 'view-expence-details', NOW()),
    (gen_random_uuid(), 'view-expenses', 'view-expenses', NOW()),
    (gen_random_uuid(), 'view-finance', 'view-finance', NOW()),
    (gen_random_uuid(), 'view-hospitals', 'view-hospitals', NOW()),
    (gen_random_uuid(), 'view-hr', 'view-hr', NOW()),
    (gen_random_uuid(), 'view-inventory', 'view-inventory', NOW()),
    (gen_random_uuid(), 'view-invoices', 'view-invoices', NOW()),
    (gen_random_uuid(), 'view-movements', 'view-movements', NOW()),
    (gen_random_uuid(), 'view-patients', 'view-patients', NOW()),
    (gen_random_uuid(), 'view-prestation-orders', 'view-prestation-orders', NOW()),
    (gen_random_uuid(), 'view-prestations', 'view-prestations', NOW()),
    (gen_random_uuid(), 'view-process-refund-request', 'view-process-refund-request', NOW()),
    (gen_random_uuid(), 'view-refund-reasons', 'view-refund-reasons', NOW()),
    (gen_random_uuid(), 'view-refund-requests', 'view-refund-requests', NOW()),
    (gen_random_uuid(), 'view-audit', 'view-audit', NOW()),
    (gen_random_uuid(), 'view-reports', 'view-reports', NOW()),
    (gen_random_uuid(), 'view-settings', 'view-settings', NOW()),
    (gen_random_uuid(), 'view-supplier-categories', 'view-supplier-categories', NOW()),
    (gen_random_uuid(), 'view-suppliers', 'view-suppliers', NOW()),
    (gen_random_uuid(), 'view-support', 'view-support', NOW()),
    (gen_random_uuid(), 'view-test-order-assignments', 'view-test-order-assignments', NOW()),
    (gen_random_uuid(), 'view-test-orders', 'view-test-orders', NOW()),
    (gen_random_uuid(), 'view-tests', 'view-tests', NOW()),
    (gen_random_uuid(), 'view-tickets', 'view-tickets', NOW()),
    (gen_random_uuid(), 'view-users', 'view-users', NOW());

INSERT INTO branches (id, name, code, location, created_at, updated_at)
VALUES ('00000000-0000-0000-0000-000000000001', 'Siège', 'SIEGE', 'Cotonou', NOW(), NOW());

INSERT INTO roles (id, branch_id, name, slug, description, is_assignable, is_protected, created_at, updated_at)
VALUES ('22222222-2222-2222-2222-222222222222',
        '00000000-0000-0000-0000-000000000001',
        'Administrateur', 'admin', 'Accès complet — tests', TRUE, FALSE, NOW(), NOW());

INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-222222222222', p.id FROM permissions p;
